import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import llm_provider


class _Completed:
    returncode = 0
    stdout = ""
    stderr = ""


def test_openai_provider_can_delegate_to_codex_cli(monkeypatch):
    captured = {}

    def fake_run(args, input, **kwargs):
        captured["args"] = args
        captured["input"] = input
        captured["kwargs"] = kwargs
        output_path = Path(args[args.index("--output-last-message") + 1])
        output_path.write_text("Generated by Codex", encoding="utf-8")
        return _Completed()

    monkeypatch.setattr(llm_provider, "get_openai_use_codex_cli", lambda: True)
    monkeypatch.setattr(llm_provider, "get_codex_cli_command", lambda: "codex")
    monkeypatch.setattr(llm_provider, "get_codex_cli_model", lambda: "")
    monkeypatch.setattr(llm_provider, "get_codex_cli_sandbox", lambda: "read-only")
    monkeypatch.setattr(llm_provider, "get_codex_cli_timeout_seconds", lambda: 123)
    monkeypatch.setattr(llm_provider, "get_openai_reasoning_effort", lambda: "xhigh")
    monkeypatch.setattr(subprocess, "run", fake_run)

    text = llm_provider._generate_text_openai("Write one video title.", model="gpt-test")

    assert text == "Generated by Codex"
    assert captured["args"][:3] == ["codex", "-c", 'model_reasoning_effort="xhigh"']
    assert captured["args"][captured["args"].index("--ask-for-approval") + 1] == "never"
    assert captured["args"][-1] == "-"
    assert captured["args"][captured["args"].index("--model") + 1] == "gpt-test"
    assert captured["args"][captured["args"].index("--sandbox") + 1] == "read-only"
    assert captured["kwargs"]["timeout"] == 123
    assert "Write one video title." in captured["input"]
    assert "Return only the final text requested" in captured["input"]


def test_codex_cli_missing_raises_clear_error(monkeypatch):
    def fake_run(*_args, **_kwargs):
        raise FileNotFoundError("codex")

    monkeypatch.setattr(llm_provider, "get_openai_use_codex_cli", lambda: True)
    monkeypatch.setattr(llm_provider, "get_codex_cli_command", lambda: "codex")
    monkeypatch.setattr(llm_provider, "get_codex_cli_model", lambda: "")
    monkeypatch.setattr(llm_provider, "get_codex_cli_sandbox", lambda: "read-only")
    monkeypatch.setattr(llm_provider, "get_codex_cli_timeout_seconds", lambda: 123)
    monkeypatch.setattr(llm_provider, "get_openai_reasoning_effort", lambda: "xhigh")
    monkeypatch.setattr(subprocess, "run", fake_run)

    with pytest.raises(RuntimeError, match="Codex CLI was not found"):
        llm_provider._generate_text_openai("Write one video title.", model="")
